spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forumdb
    username: forum_user
    password: forum
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              create-target: /create.sql
#              action: create
#              create-source: metadata
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  flyway:
    enabled: true
    locations: classpath:db/migration
